// react-app/src/App.js
import React, { Component } from 'react';
import './styles.css';
import { lineString } from './graph';

class App extends Component {
  render() {
    return (
      <div className="App">
        <h2>My awesome React app</h2>
        <svg>
          <path d={ lineString } />
        </svg>
      </div>
    );
  }
}

export default App;

// angular-app/src/app/app.component.ts
import { Component } from '@angular/core';
import { lineString } from '../graph';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  pathString = lineString;
}

<div>
  <h2>My awesome Angular app</h2>
  <svg>
    <path [attr.d]="pathString" />
  </svg>
</div>
